CREATE TABLE produto (
  id SERIAL PRIMARY KEY,
  descricao VARCHAR(255) NOT NULL,
  cor VARCHAR(50),
  largura DECIMAL,
  altura DECIMAL,
  comprimento DECIMAL
);

CREATE TABLE USUARIO(
	IDUSUARIO SERIAL PRIMARY KEY,
	USUARIO VARCHAR(50),
	SENHA VARCHAR(20),
	SEXO CHAR,
	SETOR VARCHAR(50)
)
