CREATE TABLE produto (
  id SERIAL PRIMARY KEY,
  descricao VARCHAR(255) NOT NULL,
  cor VARCHAR(50),
  largura DECIMAL,
  altura DECIMAL,
  comprimento DECIMAL
);

CREATE TABLE USUARIO(
	IDUSUARIO SERIAL PRIMARY KEY,
	USUARIO VARCHAR(50),
	SENHA VARCHAR(20),
	SEXO CHAR,
	SETOR VARCHAR(50)
);

CREATE TABLE ENDERECO(
IDENDERECO SERIAL PRIMARY KEY,
RUA VARCHAR(50),
CIDADE VARCHAR(50),
CEP VARCHAR(50),
BAIRRO VARCHAR(50),
UF VARCHAR(2)
);

CREATE TABLE CLIENTE(
IDCLIENTE SERIAL PRIMARY KEY,
FANTASIA VARCHAR(30),
CNPJ VARCHAR(20),
RAZAOSOCIAL VARCHAR(50),
IDENDERECO INT,
CONSTRAINT FK_IDENDERECO FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO(IDENDERECO),
EMAIL VARCHAR(30)
);

CREATE TABLE REVENDA(
IDREVENDA SERIAL PRIMARY KEY,
IDENDERECO INT,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO(IDENDERECO),
IDCLIENTE INT,
CONSTRAINT FK_IDCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
NUMERO INT,
CNPJ VARCHAR(30),
EMAIL VARCHAR(50)
);

CREATE TABLE FORNECEDOR(
IDFORNECEDOR SERIAL PRIMARY KEY,
FANTASIA VARCHAR(50),
RAZAOSOCIAL VARCHAR(50),
CNPJ VARCHAR(20),
MATERIAPRIMA VARCHAR(50),
EMAIL VARCHAR(40)
);

CREATE TABLE ESTADONOTA(
IDESTADONOTA SERIAL PRIMARY KEY,
NUMERONOTA VARCHAR(20),
ESTAD0 VARCHAR(40),
UF VARCHAR(2)
);

CREATE TABLE NOTASAIDA(
IDSAIDA SERIAL PRIMARY KEY,
IDESTADONOTA INT,
CONSTRAINT FK_ESTADONOTA FOREIGN KEY (IDESTADONOTA) REFERENCES ESTADONOTA(IDESTADONOTA),
NUMERONF INT,
VALORTOTAL DECIMAL(10,2),
DATAEMISAO DATE,
IDCLIENTE INT,
CONSTRAINT FK_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE NOTAENTRADA(
IDENTRADA SERIAL PRIMARY KEY,
IDESTADONOTA INT,
CONSTRAINT FK_ESTADONOTA FOREIGN KEY (IDESTADONOTA) REFERENCES ESTADONOTA(IDESTADONOTA),
NUMERONF INT,
VALORTOTAL DECIMAL(10,2),
DATAEMISAO DATE,
IDFORNECEDOR INT,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
)

